version: "3.9"
services:
  database:
    image: "postgres:latest"
    container_name: "DB_bn"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  pgAdmin:
    image: dpage/pgadmin4
    container_name: "DB_bn_visualize"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes: 
      - pgAdmin:/root/.pgadmin
    ports:
      - 5050:80

volumes:
    postgres:
    pgAdmin: